export const CREATE_CHALLENGE_ROOM_REQUESTED =
  "CHALLENGE: CREATE_CHALLENGE_ROOM_REQUESTED";
export const CREATE_CHALLENGE_ROOM_SUCCESS =
  "CHALLENGE: CREATE_CHALLENGE_ROOM_SUCCESS";
export const CREATE_CHALLENGE_ROOM_FAILED =
  "CHALLENGE: CREATE_CHALLENGE_ROOM_FAILED";
export const TICK = "CHALLENGE: TICK";
export const START_COUNT_DOWN = "CHALLENGE: START_COUNT_DOWN";
export const STOP_COUNT_DOWN = "CHALLENGE: STOP_COUNT_DOWN";
export const RESET_COUNT_DOWN = "CHALLENGE: RESET_COUNT_DOWN";
export const COUNT_DOWN_TIMEOUT = "CHALLENGE: COUNT_DOWN_TIMEOUT";
export const START_TICK = "CHALLENGE: START_TICK";
export const FAIL_TICK = "CHALLENGE: FAIL_TICK";
export const FAIL_COUNT_DONW = "CHALLENGE: FAIL_COUNT_DONW";
export const FETCH_QUESTIONS_REQUESTED = "CHALLENGE: FETCH_QUESTIONS_REQUESTED";
export const FETCH_QUESTIONS_SUCCEEDED = "CHALLENGE: FETCH_QUESTIONS_SUCCEEDED";
export const FETCH_QUESTIONS_FAILED = "CHALLENGE: FETCH_QUESTIONS_FAILED";
export const REQUEST_NEXT_QUESTION = "CHALLENGE: REQUEST_NEXT_QUESTION";
export const INIT_QUESTION_ITERATOR = "CHALLENGE: INIT_QUESTION_ITERATOR";
export const SHOW_NEXT_QUESTION = "CHALLENGE: SHOW_NEXT_QUESTION";
export const NO_MORE_QUESTIONS = "CHALLENGE: NO_MORE_QUESTIONS";
export const SHOW_ANSWER = "CHALLENGE: SHOW_ANSWER";
export const ADD_USER_ANSWERS = "CHALLENGE: ADD_USER_ANSWERS";
export const SUBMIT_USER_ANSWERS_REQUESTED =
  "CHALLENGE: SUBMIT_USER_ANSWERS_REQUESTED";
export const RESET_CHALLENGE_STATE = "CHALLENGE: RESET_CHALLENGE_STATE";
export const RESET_CHALLENGE_ANSWER_STATE =
  "CHALLENGE: RESET_CHALLENGE_ANSWER_STATE";
export const STOP_EXAM = "CHALLENGE: STOP_EXAM";
export const CHANGE_CHOICE = "CHALLENGE: CHANGE_CHOICE";
export const CONFIRM_CHOICE = "CHALLENGE: CONFIRM_CHOICE";
export const ADD_CHOICE = "CHALLENGE: ADD_CHOICE";
export const DELETE_CHOICE = "CHALLENGE: DELETE_CHOICE";
export const GAIN_SCORE = "CHALLENGE: GAIN_SCORE";
export const ADD_CHALLENGE_SCORE = "CHALLENGE: ADD_CHALLENGE_SCORE";
export const FETCH_CHALLENGE_RECORD_REQUESTED =
  "CHALLENGE: FETCH_CHALLENGE_RECORD_REQUESTED";
export const FETCH_CHALLENGE_RECORD_SUCCEEDED =
  "CHALLENGE: FETCH_CHALLENGE_RECORD_SUCCEEDED";
export const FETCH_CHALLENGE_RECORD_FAILED =
  "CHALLENGE: FETCH_CHALLENGE_RECORD_FAILED";
export const SHOW_CHALLENGE_RECORD = "CHALLENGE: SHOW_CHALLENGE_RECORD";
export const EXIT_CHALLENGE_ROOM = "CHALLENGE: EXIT_CHALLENGE_ROOM";
export const FETCH_CHALLENGE_INFOMATION_REQUESTED =
  "CHALLENGE: FETCH_CHALLENGE_INFOMATION_REQUESTED";
export const FETCH_CHALLENGE_INFOMATION_SUCCEEDED =
  "CHALLENGE: FETCH_CHALLENGE_INFOMATION_SUCCEEDED";
export const FETCH_CHALLENGE_INFOMATION_FAILED =
  "CHALLENGE: FETCH_CHALLENGE_INFOMATION_FAILED";
export const SET_CHALLENGE_ID = "CHALLENGE: SET_CHALLENGE_ID";
export const DURATION = 15;
export const SCORE_GAIN_PER_QUESTION = 5;
