export const FETCH_ALL_INFORMATION_REQUESTED =
  "INFO: FETCH_ALL_INFORMATION_REQUESTED";
export const FETCH_ALL_INFORMATION_SUCCEED =
  "INFO: FETCH_ALL_INFORMATION_SUCCEED";
export const FETCH_ALL_INFORMATION_FAILED =
  "INFO: FETCH_ALL_INFORMATION_FAILED";
export const KNOWLEDGE_INFORMATION_REQUESTED =
  "INFO: KNOWLEDGE_INFORMATION_REQUESTED";
export const KNOWLEDGE_INFORMATION_SUCCEED =
  "INFO: KNOWLEDGE_INFORMATION_SUCCEED";
export const KNOWLEDGE_INFORMATION_FAILED =
  "INFO: KNOWLEDGE_INFORMATION_FAILED";
export const ADD_KNOWLEDGE_SCORE = "INFO: ADD_KNOWLEDGE_SCORE";
export const RANK_INFORMATION_REQUESTED = "INFO: RANK_INFORMATION_REQUESTED";
export const RANK_INFORMATION_SUCCEED = "INFO: RANK_INFORMATION_SUCCEED";
export const RANK_INFORMATION_FAILED = "INFO: RANK_INFORMATION_FAILED";
export const ADD_RANK_SCORE = "INFO: ADD_RANK_SCORE";
export const SEASON_INFORMATION_REQUESTED =
  "INFO: SEASON_INFORMATION_REQUESTED";
export const SEASON_INFORMATION_SUCCEED = "INFO: SEASON_INFORMATION_SUCCEED";
export const SEASON_INFORMATION_FAILED = "INFO: SEASON_INFORMATION_FAILED";
export const FETCH_TOTAL_RANK_REQUETED = "INFO: FETCH_TOTAL_RANK_REQUETED";
export const FETCH_TOTAL_RANK_SUCCEED = "INFO: FETCH_TOTAL_RANK_SUCCEED";
export const FETCH_TOTAL_RANK_FAILED = "INFO: FETCH_TOTAL_RANK_FAILED";
export const FETCH_SCHOOL_RANK_REQUETED = "INFO: FETCH_SCHOOL_RANK_REQUETED";
export const FETCH_SCHOOL_RANK_SUCCEED = "INFO: FETCH_SCHOOL_RANK_SUCCEED";
export const FETCH_SCHOOL_RANK_FAILED = "INFO: FETCH_SCHOOL_RANK_FAILED";
export const FETCH_COLLEGE_RANK_REQUETED = "INFO: FETCH_COLLEGE_RANK_REQUETED";
export const FETCH_COLLEGE_RANK_SUCCEED = "INFO: FETCH_COLLEGE_RANK_SUCCEED";
export const FETCH_COLLEGE_RANK_FAILED = "INFO: FETCH_COLLEGE_RANK_FAILED";
