export const TOGGLE_MORE = "MATCH: TOGGLE_MORE";
export const TOGGLE_NO = "MATCH: TOGGLE_NO";
export const GAME_HISTORY = "MATCH: GAME_HISTORY";
export const ROOM_PASSWORD = "MATCH: ROOM_PASSWORD";
export const TICK = "MATCH: TICK";
export const START_COUNT_DOWN = "MATCH: START_COUNT_DOWN";
export const STOP_COUNT_DOWN = "MATCH: STOP_COUNT_DOWN";
export const RESET_COUNT_DOWN = "MATCH: RESET_COUNT_DOWN";
export const COUNT_DOWN_TIMEOUT = "MATCH: COUNT_DOWN_TIMEOUT";
export const START_TICK = "MATCH: START_TICK";
export const FAIL_TICK = "MATCH: FAIL_TICK";
export const FAIL_COUNT_DONW = "MATCH: FAIL_COUNT_DONW";
export const FETCH_QUESTIONS_REQUESTED = "MATCH: FETCH_QUESTIONS_REQUESTED";
export const FETCH_QUESTIONS_SUCCEEDED = "MATCH: FETCH_QUESTIONS_SUCCEEDED";
export const FETCH_QUESTIONS_FAILED = "MATCH: FETCH_QUESTIONS_FAILED";
export const REQUEST_NEXT_QUESTION = "MATCH: REQUEST_NEXT_QUESTION";
export const INIT_QUESTION_ITERATOR = "MATCH: INIT_QUESTION_ITERATOR";
export const SHOW_NEXT_QUESTION = "MATCH: SHOW_NEXT_QUESTION";
export const NO_MORE_QUESTIONS = "MATCH: NO_MORE_QUESTIONS";
export const SHOW_ANSWER = "MATCH: SHOW_ANSWER";
export const ADD_USER_ANSWERS = "MATCH: ADD_USER_ANSWERS";
export const SUBMIT_USER_ANSWERS_REQUESTED =
  "MATCH: SUBMIT_USER_ANSWERS_REQUESTED";
export const RESET_MATCH_STATE = "MATCH: RESET_MATCH_STATE";
export const STOP_EXAM = "MATCH: STOP_EXAM";
export const CHANGE_CHOICE = "MATCH: CHANGE_CHOICE";
export const CONFIRM_CHOICE = "MATCH: CONFIRM_CHOICE";
export const ADD_CHOICE = "MATCH: ADD_CHOICE";
export const DELETE_CHOICE = "MATCH: DELETE_CHOICE";
export const GAIN_SCORE = "MATCH: GAIN_SCORE";
export const JOIN_MATCH_REQUESTED = "MATCH: JOIN_MATCH_REQUESTED";
export const JOIN_MATCH_SUCCESSED = "MATCH: JOIN_MATCH_SUCCESSED";
export const JOIN_MATCH_FAILED = "MATCH: JOIN_MATCH_FAILED";
export const RESET_EXERCISE_RELATED = "MATCH: RESET_EXERCISE_RELATED";
export const FETCH_MATCH_HISTORY_REQUESTED =
  "MATCH: FETCH_MATCH_HISTORY_REQUESTED";
export const FETCH_MATCH_HISTORY_SUCCEEDED =
  "MATCH: FETCH_MATCH_HISTORY_SUCCEEDED";
export const FETCH_MATCH_HISTORY_FAILED = "MATCH: FETCH_MATCH_HISTORY_FAILED";
export const SHOW_MATCH_HISTORY = "MATCH: SHOW_MATCH_HISTORY";
export const CHECK_MATCH_STATUS_REQUESTED =
  "MATCH: CHECK_MATCH_STATUS_REQUESTED";
export const CHECK_MATCH_STATUS_SUCCEED = "MATCH: CHECK_MATCH_STATUS_SUCCEED";
export const CHECK_MATCH_STATUS_FAILED = "MATCH: CHECK_MATCH_STATUS_FAILED";
export const SHOW_LOADING = "MATCH: SHOW_LOADING";
export const HIDE_LOADING = "MATCH: HIDE_LOADING";
export const DURATION = 15;
export const SCORE_GAIN_PER_QUESTION = 5;

export const OPPONENT_GAIN_SCORE = "RANK: OPPONENT_GAIN_SCORE";
export const FAIL_OPPONENT_SCORE = "RANK: FAIL_OPPONENT_SCORE";
export const STOP_OPPONENT_SCORE = "RANK: STOP_OPPONENT_SCORE";

export const CLOSE_ALERT_IMAGE = "RANK: CLOSE_ALERT_IMAGE";
export const INITIAL_ALERT_IMAGE = "RANK: INITIAL_ALERT_IMAGE";

// 对手分数增长保底时间
export const GUARANTEED_TIME = 3;
// 对手分数增长保底时间
export const TIME_RATIO = 1;
