export const FETCH_NEWS_REQUESTED = "NEWS: FETCH_NEWS_REQUESTED";
export const FETCH_NEWS_SUCCEED = "NEWS: FETCH_NEWS_SUCCEED";
export const FETCH_NEWS_FAILED = "NEWS: FETCH_NEWS_FAILED";
export const FETCH_MORE_NEWS_REQUESTED = "NEWS: FETCH_MORE_NEWS_REQUESTED";
export const FETCH_MORE_NEWS_FAILED = "NEWS: FETCH_MORE_NEWS_FAILED";
export const NEXT_PAGE = "NEWS: NEXT_PAGE";
export const NEW_INFO = 'NEWS: NEW_INFO';
export const one = 1;
