export const LOGIN = "USER: LOGIN";
export const LOGOUT = "USER: LOGOUT";
export const GET_WX_CODE = "USER: GET_WX_CODE";
export const GET_WX_CODE_SUCCEED = "USER: GET_WX_CODE_SUCCEED";
export const GET_WX_CODE_FAILED = "USER: GET_WX_CODE_FAILED";
export const GET_USER_INFO = "USER: GET_USER_INFO";
export const GET_USER_INFO_SUCCEED = "USER: GET_USER_INFO_SUCCEED";
export const GET_USER_INFO_FAILED = "USER: GET_USER_INFO_FAILED";
export const SHOW_AUTHORIZATION_WINDOW = "USER: SHOW_AUTHORIZATION_WINDOW";
export const CLOSE_AUTHORIZATION_WINDOW = "USER: CLOSE_AUTHORIZATION_WINDOW";
export const LOGIN_SUCCEED = "USER: LOGIN_SUCCEED";
export const LOGIN_FAILED = "USER: LOGIN_FAILED";
export const FETCH_OPPONENT_INFO_REQUESTED =
  "USER: FETCH_OPPONENT_INFO_REQUESTED";
export const FETCH_OPPONENT_INFO_SUCCEEDED =
  "USER: FETCH_OPPONENT_INFO_SUCCEEDED";
export const FETCH_OPPONENT_INFO_FAILED = "USER: FETCH_OPPONENT_INFO_FAILED";
export const CLEAR_OPPONENT_INFO = "USER: CLEAR_OPPONENT_INFO";
